### ISSUE TITLE
The bleu metric value is always 0

### ISSUE THREAD

**Issue by Enihsuns** [rpryzant/delete_retrieve_generate#1] opened 2019-03-11 17:24 UTC
When using the sample_config.json to run the code, the bleu metric value is always 0. Why?

I use the same command provided in Readme to run the code and I didn't alter the code.

My log:
2019-03-11 13:22:21,646 - INFO - EPOCH: 15 ITER: 48.0/50.0 WPS: 175.62 LOSS: 6.4455 METRIC: 0.0000
2019-03-11 13:22:21,759 - INFO - EPOCH: 15 ITER: 49.0/50.0 WPS: 178.09 LOSS: 6.6800 METRIC: 0.0000
2019-03-11 13:22:21,760 - INFO - EPOCH 15 COMPLETE. EVALUATING...
80/100...2019-03-11 13:22:26,620 - INFO - METRIC: 0. TIME: 4.86s CHECKPOINTING...

Thank you!

**Comment by rpryzant** [comment] 2019-03-11 23:43
This is because the sample data are too small to learn anything useful from. If you look at losses (`6.6800`) your model hadn't converged either.

I've updated the readme with instructions to reproduce the paper. Marking as this as closed.

**Closed by rpryzant** 2019-03-11 23:43 UTC
